import { t } from './build';
import type { PhaseSpec } from './types';

export const PHASES_30_39: PhaseSpec[] = [
  {
    key: 'p30',
    number: 30,
    title: 'LLM Evaluation',
    summary: 'The discipline that turns "it seems better" into a claim you can defend in review.',
    tracks: ['agentic-ai'],
    topics: [
      t('eval-as-engineering', 'Evaluation as Engineering', 'golden sets, offline versus online eval, what a score means, and what it cannot show.', 'evaluation', ['llm-nondeterminism', 'deterministic-tests'], ['testing-pyramid']),
      t('golden-set-design', 'Dataset and Golden Set Design', 'coverage of real traffic, edge cases, adversarial samples, and a set that stops being updated.', 'evaluation', ['eval-as-engineering'], ['data-modeling', 'sql-fundamentals']),
      t('llm-as-judge', 'Rubrics and LLM-as-Judge', 'scoring criteria, judge bias, position effects, and calibrating the judge against a human.', 'evaluation', ['eval-as-engineering', 'structured-output-and-tool-calls'], ['prompt-and-model-versioning']),
      t('eval-statistics', 'Statistics for Evaluation', 'variance across runs, confidence, paired comparisons, and the regression inside the noise.', 'evaluation', ['eval-as-engineering'], ['complexity-analysis', 'dp-greedy']),
      t('regression-evals-in-ci', 'Evals in the Pipeline', 'gate a prompt or model change on eval, cost of running them, and who owns the failing score.', 'evaluation', ['llm-as-judge', 'ci-migrations'], ['performance-regressions-in-ci']),
      t('human-in-the-loop-eval', 'Human Evaluation and Annotation', 'sampling for review, inter-annotator agreement, and the label that encoded a guess.', 'evaluation', ['golden-set-design'], ['review-craft']),
      t('production-eval-and-feedback', 'Evaluating in Production', 'online signals, implicit feedback, drift detection, and a score that stays honest under traffic.', 'evaluation', ['regression-evals-in-ci', 'observability-golden-signals'], ['slos-and-error-budgets']),
    ],
  },
  {
    key: 'p31',
    number: 31,
    title: 'Agent Engineering',
    summary: 'Loops, tools, budgets, guardrails \u2014 and a firm answer to when an agent is the wrong tool.',
    tracks: ['agentic-ai'],
    topics: [
      t('what-an-agent-is', 'What an Agent Actually Is', 'goal, loop, tools, state, termination criterion, and the deterministic workflow it replaced.', 'agents', ['structured-output-and-tool-calls', 'eval-as-engineering'], ['state-machines-handrolled']),
      t('tool-design-and-schemas', 'Tool Design', 'narrow tools, argument schemas, error shapes the model can act on, and the tool that is really a shell.', 'agents', ['what-an-agent-is', 'typed-boundaries'], ['validation-error-contracts']),
      t('agent-loops-and-termination', 'Loops, Budgets and Termination', 'max turns, stuck states, budget exhaustion, and the exit condition you can test.', 'agents', ['state-machines-handrolled', 'what-an-agent-is'], ['race-conditions']),
      t('planning-and-decomposition', 'Planning and Decomposition', 'task graphs, checkpoints, re-planning, and the plan that quietly became a runtime.', 'agents', ['agent-loops-and-termination', 'solid-as-consequences'], ['design-method']),
      t('guardrails-and-permissions', 'Guardrails and Permissions', 'what the agent may read, write, spend and delete, approval gates, and reversible actions.', 'agents', ['tool-design-and-schemas', 'threat-modeling'], ['secrets-and-crypto-hygiene']),
      t('agent-cost-and-latency', 'Agent Cost and Latency', 'tokens per turn, compounding loops, p99 for a multi-step run, and the price of one bad iteration.', 'agents', ['agent-loops-and-termination', 'cost-latency-quality-trilemma'], ['capacity-and-cost']),
      t('when-not-to-use-an-agent', 'When NOT to Use an Agent', 'the baseline that is cheaper, faster and testable, and the evidence that made you choose.', 'agents', ['planning-and-decomposition', 'production-eval-and-feedback'], ['when-rag-is-wrong']),
      t('multi-agent-orchestration', 'Multi-Agent Orchestration', 'shared state, handoffs, contention, and the coordination cost one agent would have avoided.', 'agents', ['when-not-to-use-an-agent'], ['event-driven-architecture', 'distributed-transactions-and-sagas']),
    ],
  },
  {
    key: 'p32',
    number: 32,
    title: 'LangGraph and Agent Runtimes',
    summary: 'The abstraction is only appreciable against the state machine you already hand-rolled.',
    tracks: ['agentic-ai'],
    topics: [
      t('graphs-and-state-machines-review', 'Graphs and State Machines, Reviewed', 'nodes, edges, cycles, reachability, and why an agent loop is a graph with a budget.', 'langgraph', ['graph-traversal', 'state-machines-handrolled'], ['recursion']),
      t('langgraph-state-and-nodes', 'LangGraph State, Nodes, Reducers', 'typed state channels, node contracts, reducers, and the merge that lost an update.', 'langgraph', ['graphs-and-state-machines-review', 'tool-design-and-schemas'], ['conditional-mapped-types']),
      t('routing-and-conditional-edges', 'Conditional Edges and Routing', 'router functions, guard conditions, parallel branches, and the cycle that never terminates.', 'langgraph', ['langgraph-state-and-nodes'], ['agent-loops-and-termination']),
      t('checkpointing-and-resume', 'Checkpointing, Resume, Time Travel', 'persisted state, replay, resuming days later, and the schema your checkpoints must survive.', 'langgraph', ['routing-and-conditional-edges', 'wal-recovery'], ['postgres-as-vector-store', 'optimistic-vs-pessimistic']),
      t('human-in-the-loop-interrupts', 'Interrupts and Human Approval', 'pause at the dangerous step, resume with a decision, and the timeout on a human.', 'langgraph', ['checkpointing-and-resume', 'guardrails-and-permissions'], ['human-in-the-loop-eval']),
      t('subgraphs-and-composition', 'Subgraphs and Composition', 'nesting, shared versus private state, versioning a subgraph, and the graph that became a codebase.', 'langgraph', ['routing-and-conditional-edges'], ['multi-agent-orchestration']),
      t('langgraph-vs-plain-code', 'LangGraph versus Plain TypeScript', 'what the runtime buys, what it costs in debugging, and the workflow that did not need it.', 'langgraph', ['subgraphs-and-composition', 'when-not-to-use-an-agent'], ['pattern-by-problem']),
    ],
  },
  {
    key: 'p33',
    number: 33,
    title: 'Agent Memory and Context',
    summary: 'What the agent knows next turn, what it stores forever, and what it is not allowed to keep.',
    tracks: ['agentic-ai'],
    topics: [
      t('memory-architecture', 'Memory Architecture', 'working, session, long-term memory: read paths, write paths, and who decides what persists.', 'agents', ['context-engineering', 'langgraph-state-and-nodes'], ['cache-patterns']),
      t('conversation-state-and-summarisation', 'Conversation State and Summarisation', 'rolling summaries, eviction, and the detail that mattered three turns later.', 'agents', ['memory-architecture'], ['llm-call-hygiene']),
      t('memory-retrieval-vs-parameters', 'Retrieved Memory versus Fine-Tuned Memory', 'store it, retrieve it, or train it in, and the update that has to be instant.', 'agents', ['memory-architecture', 'fine-tuning-vs-retrieval-vs-prompting'], ['postgres-as-vector-store']),
      t('memory-invalidation-and-conflicts', 'Memory Invalidation and Contradiction', 'stale facts, superseded beliefs, conflict resolution, and the assistant that confidently disagrees with itself.', 'agents', ['conversation-state-and-summarisation', 'cache-invalidation'], ['time-ordering-and-clocks']),
      t('context-budgets-under-limits', 'Context Budgets Under Hard Limits', 'token ceilings, prioritisation, compression, and the failure mode when everything is important.', 'agents', ['memory-architecture', 'llm-streaming-and-cancellation'], ['cost-latency-quality-trilemma']),
      t('memory-privacy-and-retention', 'Privacy, Retention and Deletion', 'what may be remembered about a person, retention windows, and deletion that reaches every index.', 'agents', ['memory-architecture', 'threat-modeling'], ['owasp-in-apis', 'backup-and-disaster-recovery']),
    ],
  },
  {
    key: 'p34',
    number: 34,
    title: 'Model Context Protocol and Tool Ecosystems',
    summary: 'A standard interface beats N one-off integrations \u2014 and brings a new trust boundary.',
    tracks: ['agentic-ai'],
    topics: [
      t('tool-protocol-problem', 'The Tool Protocol Problem', 'N models by M tools, why a standard interface wins, and what standardisation gives up.', 'mcp', ['adapter-decorator-proxy', 'tool-design-and-schemas'], ['api-and-storage-design']),
      t('mcp-server-anatomy', 'MCP Server Anatomy', 'tools, resources, prompts, transports, capability negotiation, and error semantics.', 'mcp', ['tool-protocol-problem', 'llm-call-hygiene'], ['validation-error-contracts']),
      t('mcp-client-integration', 'Integrating an MCP Client', 'discovery, tool selection pressure, context cost of a large catalog, and the agent that picks wrongly.', 'mcp', ['mcp-server-anatomy', 'agent-loops-and-termination'], ['context-engineering']),
      t('mcp-security-trust-boundaries', 'MCP Security Boundaries', 'tool poisoning, prompt injection through retrieved content, confused deputy, consent UX.', 'security', ['mcp-server-anatomy', 'owasp-in-apis'], ['guardrails-and-permissions']),
      t('mcp-vs-direct-tools', 'MCP versus Direct Tool Calls', 'when a shared server earns its operational cost, and when a function call is the right answer.', 'mcp', ['mcp-client-integration', 'langgraph-vs-plain-code'], ['when-not-to-use-an-agent']),
    ],
  },
  {
    key: 'p35',
    number: 35,
    title: 'AI Coding Agents',
    summary: 'An agent that edits a repository must be verified, sandboxed, and measured \u2014 in that order.',
    tracks: ['agentic-ai'],
    topics: [
      t('agentic-coding-loop', 'The Coding Loop', 'plan, read, edit, run, observe, iterate, and where the loop diverges from a senior engineer.', 'agents', ['mcp-vs-direct-tools', 'agent-cost-and-latency'], ['branching-and-merging']),
      t('repo-context-and-retrieval', 'Repository Context', 'dependency graphs, symbol retrieval, relevant-file selection, and the context window full of noise.', 'rag', ['rag-pipeline-engineering', 'git-object-model'], ['context-budgets-under-limits']),
      t('sandboxing-and-execution', 'Sandboxed Execution', 'filesystem and network isolation, secrets visibility, resource limits, and the test that ran rm.', 'security', ['mcp-security-trust-boundaries', 'containers-are-processes'], ['resource-limits-and-oom']),
      t('diff-review-and-verification', 'Never Trust an Unverified Patch', 'scope drift, drive-by refactors, running the suite, and reading a diff as a reviewer.', 'agents', ['agentic-coding-loop', 'review-craft', 'deterministic-tests'], ['contract-testing']),
      t('test-generation-and-repair', 'Test Generation and Repair', 'tests that assert the buggy behaviour, coverage theatre, and using tests to converge the patch.', 'testing', ['diff-review-and-verification', 'property-and-mutation-testing'], ['testing-broken-code']),
      t('code-agent-evaluation', 'Evaluating a Coding Agent', 'pass@k on real tasks, flaky suites, hidden tests, and a benchmark the agent has effectively seen.', 'evaluation', ['test-generation-and-repair', 'regression-evals-in-ci'], ['eval-statistics']),
      t('coding-agent-observability', 'Observing an Agent at Work', 'turn traces, tool-call audit, cost per merged PR, and the intervention point a human needs.', 'observability', ['code-agent-evaluation', 'structured-logs'], ['distributed-tracing']),
    ],
  },
  {
    key: 'p36',
    number: 36,
    title: 'Agentic SDLC',
    summary: 'Agents across the whole lifecycle, with gates a team can actually enforce.',
    tracks: ['agentic-ai'],
    topics: [
      t('sdlc-as-a-graph', 'The SDLC as a Workflow Graph', 'requirements, design, implementation, test, review, release: states, owners, and transitions.', 'ai-systems', ['code-agent-evaluation', 'clean-architecture', 'ci-test-layers'], ['graphs-and-state-machines-review']),
      t('agent-owned-pipeline-stages', 'Which Stages an Agent May Own', 'delegating stages versus decisions, and the stage whose error multiplies downstream.', 'ai-systems', ['sdlc-as-a-graph', 'diff-review-and-verification'], ['when-not-to-use-an-agent']),
      t('human-approval-gates', 'Approval Gates That Are Not Theatre', 'what a human reviews, how long they have, and the button that becomes a reflex.', 'leadership', ['human-in-the-loop-interrupts', 'sdlc-as-a-graph'], ['review-craft']),
      t('traceability-and-audit', 'Traceability and Audit', 'decision to diff to test to release, provenance of generated code, and reconstructing why.', 'ai-systems', ['human-approval-gates', 'structured-logs'], ['ci-migrations']),
      t('quality-bars-for-agent-output', 'Definition of Done for Agent Output', 'the bar a patch must clear to be merged, encoded as checks rather than opinions.', 'testing', ['test-generation-and-repair', 'human-approval-gates'], ['coding-agent-observability']),
      t('team-adoption-and-process', 'Adopting Agentic Process in a Team', 'pilot scope, review load shift, skill atrophy, and measuring the change you claimed.', 'leadership', ['traceability-and-audit']),
    ],
  },
  {
    key: 'p37',
    number: 37,
    title: 'Production AI Systems',
    summary: 'LLM features fail like distributed systems and like research prototypes at the same time.',
    tracks: ['agentic-ai', 'backend', 'fullstack'],
    topics: [
      t('prompt-injection-and-exfiltration', 'Prompt Injection and Data Exfiltration', 'instructions hiding in retrieved content, tool-mediated leaks, and the boundary that must hold.', 'security', ['mcp-security-trust-boundaries', 'hallucination-and-refusal'], ['owasp-in-apis']),
      t('pii-and-content-safety', 'PII and Content Safety', 'redaction, moderation, output filtering, and the compliance promise a model cannot keep alone.', 'security', ['memory-privacy-and-retention', 'prompt-injection-and-exfiltration'], ['secrets-and-crypto-hygiene']),
      t('llm-rate-limits-and-tenancy', 'Rate Limits and Multi-Tenancy for LLMs', 'per-tenant token budgets, noisy neighbour prompts, provider quotas, and fair queuing.', 'redis', ['redis-rate-limiting', 'cost-latency-quality-trilemma', 'llm-call-hygiene'], ['multi-tenancy-and-failure-domains']),
      t('model-upgrades-and-fallback', 'Model Upgrades and Fallback Chains', 'pinning, shadow eval, provider outage, degraded modes, and the fallback nobody tested.', 'ai-systems', ['prompt-and-model-versioning', 'timeout-and-retry-budgets'], ['regression-evals-in-ci']),
      t('serving-and-inference-basics', 'Serving and Inference Basics', 'GPU memory, batching, quantisation, self-host versus API, and the latency claim per token.', 'ai-systems', ['model-selection-and-cost', 'cpu-bound-vs-io-bound'], ['autoscaling-and-elasticity']),
      t('ai-cost-observability', 'Cost Observability', 'spend per feature per tenant per request, token accounting in traces, and the alert on a bill.', 'observability', ['structured-logs', 'metrics-and-alerting'], ['llm-rate-limits-and-tenancy']),
      t('degradation-modes-for-ai-features', 'Designing the Degraded Mode', 'what the product does when the model is slow, wrong, expensive or gone.', 'system-design', ['model-upgrades-and-fallback', 'feature-flags-and-progressive-delivery'], ['rollback-and-recovery']),
      t('ai-incident-triage', 'AI Incident Triage', 'quality regressions as incidents, no error rate to page on, blast radius of a prompt change.', 'observability', ['debugging-production-slowness', 'production-eval-and-feedback', 'llm-call-hygiene'], ['incident-command-and-postmortem']),
    ],
  },
  {
    key: 'p38',
    number: 38,
    title: 'Engineering Management',
    summary: 'Decisions, estimates, reviews and ladders: the technical work of leading engineers.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('architecture-decision-records', 'Architecture Decision Records', 'context, options, decision, consequences, and the record that stops the debate restarting.', 'leadership', ['solid-as-consequences', 'modular-monolith'], ['threat-modeling']),
      t('estimation-and-complexity-tiers', 'Estimation and Complexity Tiers', 'sizing by risk and reversibility, why precision is a lie, and the spike that answers the question.', 'leadership', ['requirements-to-numbers', 'architecture-decision-records'], ['capacity-and-cost']),
      t('code-review-culture', 'Review as Mentorship Under Deadline', 'standards that survive pressure, review load, and turning a comment into a taught principle.', 'leadership', ['review-craft', 'testing-broken-code'], ['security-review-mindset']),
      t('mentoring-and-growth-ladders', 'Mentoring and Growth Ladders', 'what L3 versus L5 looks like in behaviour, feedback that changes it, and the ladder that rewards politics.', 'leadership', ['architecture-decision-records'], ['code-review-culture']),
      t('blameless-postmortems', 'Postmortems That Change Systems', 'causal chains, contributing factors, action items with owners, and the fix that ships.', 'leadership', ['incident-command-and-postmortem', 'mentoring-and-growth-ladders'], ['slos-and-error-budgets']),
      t('roadmap-and-prioritisation', 'Roadmap, Prioritisation and Sayings No', 'impact versus effort, tech debt as a balance sheet, and the cost of the deferred quarter.', 'leadership', ['estimation-and-complexity-tiers'], ['cost-latency-quality-trilemma']),
      t('platform-versus-product-thinking', 'Platform versus Product Thinking', 'building for the second team, adoption without mandate, and the abstraction others must live in.', 'system-design', ['modular-monolith', 'architecture-decision-records'], ['mcp-vs-direct-tools']),
      t('hiring-and-signal-design', 'Hiring and Interview Signal', 'questions that predict performance, structured rubrics, and the bar you actually hold.', 'leadership', ['review-craft', 'mentoring-and-growth-ladders'], ['golden-set-design']),
    ],
  },
  {
    key: 'p39',
    number: 39,
    title: 'Engineering Judgment',
    summary: 'The capstone: choosing under incomplete information, and being able to argue it.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('constraints-decide-architecture', 'Constraints Decide Architecture', 'team, deadline, traffic, budget, compliance, skills: the inputs that remove options first.', 'system-design', ['bounded-contexts', 'cap-and-pacelc', 'requirements-to-numbers'], undefined, 4),
      t('reversibility-and-option-value', 'Reversibility and Option Value', 'one-way versus two-way doors, deferring a decision honestly, and the cost of premature commitment.', 'system-design', ['constraints-decide-architecture', 'architecture-decision-records'], undefined, 4),
      t('complexity-budget', 'The Complexity Budget', 'every abstraction spent from a finite budget: who pays the interest, and when it is repaid.', 'system-design', ['reversibility-and-option-value', 'platform-versus-product-thinking'], undefined, 4),
      t('premature-abstraction-and-optimisation', 'Premature Abstraction and Premature Optimisation', 'the third use case that reveals the wrong interface, and the optimisation with no measurement.', 'system-design', ['complexity-budget', 'pattern-by-problem'], undefined, 4),
      t('build-versus-buy-versus-adopt', 'Build, Buy, or Adopt', 'total cost, lock-in, exit paths, and the vendor that becomes a dependency you cannot fire.', 'system-design', ['complexity-budget', 'cloud-primitives'], undefined, 4),
      t('judging-under-incomplete-information', 'Judging Under Incomplete Information', 'deciding with the data you have, naming the assumption, and pre-committing to the revisiting trigger.', 'leadership', ['constraints-decide-architecture', 'ai-incident-triage', 'production-eval-and-feedback'], undefined, 4),
      t('senior-capstone-review', 'The Capstone Review', 'one system argued end to end: constraints, options, trade-offs, failure modes, cost, and what you would not build.', 'system-design', ['premature-abstraction-and-optimisation', 'judging-under-incomplete-information', 'when-rag-is-wrong', 'langgraph-vs-plain-code', 'microservices-decomposition', 'design-realtime'], undefined, 5),
    ],
  },
];
