import { t } from './build';
import type { PhaseSpec } from './types';

export const PHASES_00_09: PhaseSpec[] = [
  {
    key: 'p00',
    number: 0,
    title: 'Engineering Baseline',
    summary: 'What actually happens when a program runs, before any framework exists.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('how-programs-run', 'How Programs Run', 'source, machine code, the CPU loop, registers, the stack and the heap.', 'javascript'),
      t('memory-hierarchy', 'Memory Hierarchy', 'registers, L1/L2/L3, RAM, NVMe: why locality and cache lines decide performance.', 'javascript', ['how-programs-run']),
      t('processes-threads', 'Processes and Threads', 'address spaces, context switches, scheduling, and what a thread actually costs.', 'linux', ['how-programs-run']),
      t('system-calls-io', 'System Calls and I/O', 'the kernel boundary, blocking reads, sockets, file descriptors, epoll.', 'linux', ['processes-threads']),
      t('cpu-bound-vs-io-bound', 'CPU-Bound vs I/O-Bound', 'the only distinction that matters when choosing a concurrency model.', 'node', ['system-calls-io'], ['memory-hierarchy']),
      t('networking-basics', 'Networking Basics', 'packets, latency, bandwidth, MTU, RTT as the cost unit of distributed systems.', 'http', ['system-calls-io']),
      t('concurrency-parallelism', 'Concurrency vs Parallelism', 'dealing with many things at once versus doing many things at once.', 'node', ['processes-threads'], ['cpu-bound-vs-io-bound']),
    ],
  },
  {
    key: 'p01',
    number: 1,
    title: 'JavaScript Deep Internals',
    summary: 'The language and runtime as machinery: references, scopes, the loop, streams.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('js-values-references', 'Values, References, Equality', 'primitives vs objects, copying semantics, ===, coercion rules that bite.', 'javascript', ['how-programs-run']),
      t('closures-scope', 'Closures and Lexical Scope', 'captured environments, lifetime, and the leaks they cause.', 'javascript', ['js-values-references'], ['memory-hierarchy']),
      t('prototypes', 'Prototypes and the Prototype Chain', 'delegation instead of classes, and where classes are lying to you.', 'javascript', ['js-values-references']),
      t('event-loop', 'The Event Loop', 'call stack, microtask queue, macrotask queue, drain order, output prediction.', 'javascript', ['closures-scope'], ['concurrency-parallelism']),
      t('promises-async', 'Promises, async/await, Cancellation', 'implicit continuations, Promise.all/race/any/allSettled, AbortController.', 'javascript', ['event-loop'], ['system-calls-io']),
      t('streams-backpressure', 'Streams and Backpressure', 'highWaterMark, drain, pause, and what unbounded buffering does to RSS.', 'node', ['promises-async'], ['memory-hierarchy']),
      t('node-libuv', 'libuv and the Worker Pool', 'where fs/crypto callbacks really execute, thread pool sizing, handles vs requests.', 'node', ['event-loop', 'system-calls-io'], ['promises-async']),
      t('node-process-lifecycle', 'Process Lifecycle and Graceful Shutdown', 'signals, draining in-flight work, exit codes, PM2/systemd expectations.', 'node', ['node-libuv'], ['processes-threads']),
      t('gc-memory-leaks', 'Garbage Collection and Leak Hunting', 'generations, retained references, heap snapshots, diagnostic reports.', 'javascript', ['closures-scope'], ['memory-hierarchy']),
      t('this-and-prototypes', 'this, bind/call/apply', 'receiver binding, arrow functions, and the loss of `this` in callbacks.', 'javascript', ['prototypes'], ['event-loop']),
    ],
  },
  {
    key: 'p02',
    number: 2,
    title: 'TypeScript Mastery',
    summary: 'Types as design tools, and the hard line between compile-time and runtime safety.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('structural-typing', 'Structural Typing and Assignability', 'nominal vs structural, excess property checks, variance.', 'typescript', ['js-values-references']),
      t('narrowing-unions', 'Narrowing and Discriminated Unions', 'control-flow analysis, exhaustiveness with never, illegal states made unrepresentable.', 'typescript', ['structural-typing']),
      t('generics', 'Generics and Inference', 'constraint design, infer, why generic soup is a smell.', 'typescript', ['narrowing-unions']),
      t('conditional-mapped-types', 'Conditional and Mapped Types', 'type-level programming: keyof, indexed access, template literals, utility types.', 'typescript', ['generics']),
      t('type-vs-runtime-validation', 'Type Safety Is Not Runtime Validation', 'erasure, boundaries, Zod at the edge, `as` as a lie you bet your uptime on.', 'typescript', ['narrowing-unions'], ['conditional-mapped-types']),
      t('typed-boundaries', 'Typed API and Event Boundaries', 'typed clients, Result/Either, typed event buses, config that cannot be wrong.', 'typescript', ['type-vs-runtime-validation'], ['generics']),
    ],
  },
  {
    key: 'p03',
    number: 3,
    title: 'Data Structures and Algorithms',
    summary: 'Reasoning tools, not a LeetCode treadmill. Every structure earns its place in production.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('complexity-analysis', 'Complexity Analysis', 'Big-O, constants that matter, cache locality, amortised cost.', 'system-design', ['memory-hierarchy']),
      t('language-mechanics', 'Language Mechanics for Problem Solving', 'character codes, number ranges, branch tables, loop bounds, and what an argument really carries.', 'javascript', ['js-values-references'], ['how-programs-run']),
      t('pattern-printing', 'Pattern Printing', 'nested loops read as coordinates: padding, symmetry, borders and the row-column rule behind every shape.', 'javascript', ['language-mechanics']),
      t('dsa-maths-foundations', 'Arithmetic Foundations for DSA', 'digits, divisors, primes and GCD — the loop shapes every later technique is built from.', 'javascript', ['complexity-analysis']),
      t('dsa-bit-manipulation', 'Bit Manipulation', 'masks, shifts and XOR: the arithmetic the processor actually does, and the 32-bit coercion JavaScript puts in front of every operator.', 'javascript', ['dsa-maths-foundations']),
      t('array-techniques', 'Array Techniques', 'single passes, two pointers, write indices, prefix sums: the moves that beat sorting.', 'javascript', ['dsa-maths-foundations']),
      t('hash-tables', 'Hash Tables', 'buckets, collisions, load factor, why hashing is the default O(1) answer.', 'system-design', ['complexity-analysis'], ['js-values-references']),
      t('trees-and-indexes', 'Trees and B-Trees', 'balanced trees, B-tree fanout, why disk structures differ from memory ones.', 'postgresql', ['complexity-analysis'], ['memory-hierarchy']),
      t('heaps-priority-queues', 'Heaps and Priority Queues', 'scheduling, top-K, timers, delayed jobs.', 'system-design', ['trees-and-indexes'], ['event-loop']),
      t('recursion', 'Recursion', 'stack frames, base cases, tail calls that never came, iterative rewrites.', 'javascript', ['closures-scope', 'how-programs-run']),
      t('sorting-algorithms', 'Comparison Sorting', 'selection, bubble, insertion, merge, quick: what each pass guarantees and what it costs.', 'javascript', ['array-techniques', 'recursion']),
      t('binary-search', 'Binary Search and Ordered Boundaries', 'halving a window, the index the loop exits on, and searching a matrix without flattening it.', 'javascript', ['array-techniques'], ['sorting-algorithms']),
      t('search-space', 'Searching the Answer, Not the Index', 'monotone predicates over a value range: the smallest feasible rate, capacity or distance.', 'javascript', ['binary-search']),
      t('string-techniques', 'String Algorithms', 'characters as arrays: two pointers over text, frequency maps, nesting counters and windows that never reorder what they read.', 'javascript', ['array-techniques', 'hash-tables'], ['language-mechanics']),
      t('numeric-strings', 'Numerals and Parsing', 'roman and decimal in both directions, place value, and the overflow a parser has to refuse rather than absorb.', 'javascript', ['string-techniques'], ['dsa-maths-foundations']),
      t('linked-lists', 'Linked Lists and Pointer Rewiring', 'nodes instead of indices: fast and slow walkers, reversal by re-pointing, and the sentinel that deletes the head special case.', 'javascript', ['array-techniques'], ['recursion']),
      t('graph-traversal', 'Graph Traversal and Shortest Paths', 'BFS/DFS, topological sort, Dijkstra, dependency resolution.', 'system-design', ['hash-tables'], ['recursion']),
      t('tries-autocomplete', 'Tries and Prefix Search', 'autocomplete, routing tables, tokenization costs.', 'system-design', ['hash-tables'], ['memory-hierarchy']),
      t('dp-greedy', 'Dynamic Programming and Greedy', 'overlapping subproblems, state definition, when greedy is provably right.', 'system-design', ['recursion'], ['complexity-analysis']),
      t('lru-rate-limiter', 'Applied Structures: LRU, Rate Limiter, Scheduler', 'build the three structures every backend eventually buys.', 'node', ['hash-tables', 'heaps-priority-queues'], ['streams-backpressure']),
    ],
  },
  {
    key: 'p04',
    number: 4,
    title: 'HTTP and Web Fundamentals',
    summary: 'From typed URL to rendered byte, and every millisecond in between.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('dns-resolution', 'DNS Resolution', 'records, TTLs, resolvers, caching layers, what a stale record does to failover.', 'http', ['networking-basics']),
      t('tcp-tls', 'TCP and TLS', 'handshakes, RTT costs, keep-alive, connection reuse, certificate chains.', 'http', ['networking-basics'], ['dns-resolution']),
      t('http-versions', 'HTTP/1.1, HTTP/2, HTTP/3 and QUIC', 'head-of-line blocking, multiplexing, 0-RTT, why UDP won.', 'http', ['tcp-tls']),
      t('http-caching', 'HTTP Caching', 'Cache-Control, ETag, Vary, private vs shared, invalidation you can reason about.', 'http', ['dns-resolution'], ['type-vs-runtime-validation']),
      t('proxies-load-balancers-cdn', 'Proxies, Load Balancers, CDN', 'L4 vs L7, hashing, TLS termination points, origin shield, latency geography.', 'cloud', ['tcp-tls'], ['http-versions']),
      t('cookies-cors-csrf', 'Cookies, CORS, CSRF', 'SameSite, credential routing, preflights, and the origin model.', 'security', ['http-caching'], ['tcp-tls']),
      t('url-to-render', 'URL to Render', 'the full path with a latency budget attached to every hop.', 'http', ['dns-resolution', 'tcp-tls', 'http-caching'], ['proxies-load-balancers-cdn']),
    ],
  },
  {
    key: 'p05',
    number: 5,
    title: 'REST API Engineering',
    summary: 'APIs as contracts that survive retries, bad clients, and partial failure.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('resource-modeling', 'Resource Modeling and Status Codes', 'nouns, representations, the semantics you cannot un-pick.', 'rest', ['http-versions'], ['url-to-render']),
      t('pagination-filtering', 'Pagination, Filtering, Sorting', 'offset pain, cursor pagination, stable sort keys.', 'rest', ['resource-modeling']),
      t('validation-error-contracts', 'Validation and Error Contracts', 'one error shape, machine-readable codes, no leaked internals.', 'rest', ['type-vs-runtime-validation', 'resource-modeling']),
      t('idempotency-retries', 'Idempotency, Retries, Timeouts', 'idempotency keys, retry budgets, jitter, why a timeout without one is a bug.', 'rest', ['validation-error-contracts'], ['promises-async']),
      t('rate-limit-circuit-breaker', 'Rate Limiting and Circuit Breakers', 'token bucket vs sliding window, breaker states, load shedding.', 'rest', ['idempotency-retries', 'lru-rate-limiter'], ['cpu-bound-vs-io-bound']),
      t('api-versioning-tracing', 'Versioning, Tracing, Correlation IDs', 'breaking changes without breaking clients, and finding one request in ten services.', 'rest', ['validation-error-contracts']),
    ],
  },
  {
    key: 'p06',
    number: 6,
    title: 'NestJS',
    summary: 'A framework understood as DI, a request pipeline, and lifecycle — not as magic.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('nestjs-di', 'Modules, Providers, Dependency Injection', 'why DI exists, token scopes, circular refs as a design smell.', 'nestjs', ['structural-typing'], ['prototypes']),
      t('nestjs-pipeline', 'The Request Pipeline', 'middleware, guards, interceptors, pipes, controllers, filters, in that order.', 'nestjs', ['nestjs-di', 'validation-error-contracts']),
      t('nestjs-scopes-lifecycle', 'Scopes and Lifecycle', 'singleton/request scope, the throughput cost of request providers, hooks.', 'nestjs', ['nestjs-di'], ['node-process-lifecycle']),
      t('nestjs-config-serialization', 'Config, Validation, Serialization', 'env bounds, DTOs, ClassSerializer stripping fields that must never leak.', 'nestjs', ['nestjs-pipeline'], ['type-vs-runtime-validation']),
      t('nestjs-queues-events', 'Queues and Events in Nest', 'BullMQ producers/consumers, failure policies, backoff, idempotent jobs.', 'nestjs', ['nestjs-scopes-lifecycle']),
      t('nestjs-testing', 'Testing a Nest Application', 'module overrides, real DB integration tests, e2e with the HTTP layer.', 'testing', ['nestjs-pipeline']),
    ],
  },
  {
    key: 'p07',
    number: 7,
    title: 'PostgreSQL Deep Mastery',
    summary: 'The database as a machine: pages, tuples, WAL, the planner, and lock reality.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('sql-fundamentals', 'SQL: Joins, Aggregation, Subqueries', 'the relational algebra behind every query you write.', 'postgresql'),
      t('sql-window-cte', 'CTEs, Recursive CTEs, Window Functions', 'ranking, running totals, graphs in SQL, materialisation gotchas.', 'postgresql', ['sql-fundamentals']),
      t('data-modeling', 'Data Modeling', 'keys, constraints, normalization, when to denormalise and what it costs.', 'postgresql', ['sql-fundamentals'], ['resource-modeling']),
      t('indexes-btree', 'Indexes and B-Trees', 'selectivity, composite order, covering and partial indexes, write amplification.', 'postgresql', ['trees-and-indexes', 'data-modeling']),
      t('postgres-storage', 'Pages, Tuples, Heap, Free Space', 'what a row physically is, fillfactor, HOT updates.', 'postgresql', ['data-modeling'], ['memory-hierarchy']),
      t('wal-recovery', 'WAL and Crash Recovery', 'the log is the database: fsync, checkpoints, replay, durability guarantees.', 'postgresql', ['postgres-storage'], ['system-calls-io']),
      t('mvcc-isolation', 'MVCC and Isolation Levels', 'snapshot visibility, read conflicts, phantom reads, serialization failures.', 'postgresql', ['postgres-storage', 'sql-fundamentals']),
      t('locks-deadlocks', 'Locks and Deadlocks', 'row vs table locks, SELECT FOR UPDATE, lock ordering, detection and recovery.', 'postgresql', ['mvcc-isolation'], ['concurrency-parallelism']),
      t('query-planner-explain', 'The Query Planner and EXPLAIN ANALYZE', 'cost model, statistics, when an index scan loses to a seq scan.', 'postgresql', ['indexes-btree', 'postgres-storage']),
      t('vacuum-bloat', 'Vacuum, Autovacuum, Bloat', 'dead tuples, wraparound, why a table slows down while staying the same size.', 'postgresql', ['mvcc-isolation', 'wal-recovery']),
      t('keyset-pagination', 'Pagination Performance', 'OFFSET pain, seek methods, deferred joins, index-only scans.', 'postgresql', ['query-planner-explain'], ['pagination-filtering']),
      t('connection-pooling', 'Connection Pooling and Server Scaling', 'pgbouncer modes, pool sizing math, what a connection actually costs.', 'postgresql', ['wal-recovery'], ['nestjs-scopes-lifecycle']),
    ],
  },
  {
    key: 'p08',
    number: 8,
    title: 'ORM Mastery',
    summary: 'Prisma and Sequelize as tools over SQL — never instead of it.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('orm-query-generation', 'What the ORM Actually Sends', 'query inspection, prepared statements, parameterisation, escaping.', 'postgresql', ['sql-fundamentals'], ['nestjs-config-serialization']),
      t('n-plus-one', 'N+1 and Loading Strategies', 'eager vs lazy, dataloader, why the fix is a join or a second query.', 'postgresql', ['orm-query-generation', 'indexes-btree'], ['complexity-analysis']),
      t('orm-transactions-pooling', 'Transactions and Pools Through an ORM', 'isolation levels, interactive transactions, pool starvation, timeouts.', 'postgresql', ['mvcc-isolation', 'connection-pooling'], ['orm-query-generation']),
      t('orm-migrations-locking', 'Migrations, Optimistic and Pessimistic Locking', 'schema change safety, version columns, SELECT FOR UPDATE through the ORM.', 'postgresql', ['locks-deadlocks', 'data-modeling'], ['wal-recovery']),
      t('orm-diagnosis', 'Diagnose a Correct-but-2-Second ORM Query', 'the exercise: EXPLAIN the generated SQL, find the access pattern, fix it.', 'postgresql', ['n-plus-one', 'query-planner-explain'], ['orm-transactions-pooling']),
    ],
  },
  {
    key: 'p09',
    number: 9,
    title: 'Redis and Caching',
    summary: 'Redis as a systems primitive with failure semantics, not a SET/GET box.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('redis-data-structures', 'Redis Data Structures', 'strings, hashes, sets, sorted sets, lists, streams, and their complexity.', 'redis', ['hash-tables']),
      t('redis-atomicity-lua', 'Atomicity, Pipelines, Lua', 'single-threaded command execution, INRACE correctness, MULTI, scripting.', 'redis', ['redis-data-structures'], ['concurrency-parallelism']),
      t('cache-patterns', 'Cache-Aside, Read/Write-Through, Write-Behind', 'which pattern fits which consistency requirement.', 'redis', ['postgres-storage'], ['redis-data-structures']),
      t('cache-invalidation', 'Invalidation and Staleness', 'TTL vs event-driven invalidation, versioned keys, the honest cost of stale reads.', 'redis', ['cache-patterns'], ['redis-atomicity-lua']),
      t('cache-stampede', 'Stampede, Penetration, Avalanche', 'coalescing, jitter, negative caching, locks around rebuild, measured hit ratios.', 'redis', ['cache-invalidation'], ['node-libuv']),
      t('distributed-locks', 'Distributed Locks', 'SET NX PX, leases, fencing tokens, clock assumptions, Redlock criticism.', 'distributed-systems', ['redis-atomicity-lua', 'locks-deadlocks']),
      t('redis-rate-limiting', 'Distributed Rate Limiting', 'fixed window, sliding log, token bucket in Redis, atomics across nodes.', 'redis', ['redis-atomicity-lua', 'rate-limit-circuit-breaker']),
      t('redis-queues-delayed-jobs', 'Queues and Delayed Jobs on Redis', 'lists vs streams vs sorted sets, visibility, retries, at-least-once reality.', 'distributed-systems', ['redis-data-structures'], ['idempotency-retries']),
      t('redis-failure-modes', 'When Redis Is Gone', 'AOF/RDB gaps, replication lag, fail-open vs fail-closed, memory eviction policy.', 'redis', ['cache-patterns', 'wal-recovery'], ['connection-pooling']),
    ],
  },
];
