import { t } from './build';
import type { PhaseSpec } from './types';

export const PHASES_20_29: PhaseSpec[] = [
  {
    key: 'p20',
    number: 20,
    title: 'Docker',
    summary: 'Containers are processes with boundaries: layers, networking, volumes, limits.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('containers-are-processes', 'Containers Are Processes', 'namespaces, cgroups, a filesystem view, and the isolation you can actually verify.', 'docker', ['processes-threads', 'filesystem-permissions'], ['system-calls-io']),
      t('images-and-layers', 'Images, Layers and Caching', 'how a Dockerfile becomes layers, why the order is a build-time argument, multi-stage builds.', 'docker', ['containers-are-processes'], ['shell-tooling']),
      t('docker-networking', 'Container Networking', 'bridge, host, published ports, intra-network DNS, and the container that cannot resolve its DB.', 'docker', ['images-and-layers', 'networking-from-the-box'], ['dns-resolution']),
      t('volumes-and-secrets', 'Volumes, Bind Mounts, Config and Secrets', 'where state lives, what a bind mount does to permissions, and the secret in an image layer.', 'docker', ['images-and-layers', 'filesystem-permissions'], ['wal-recovery']),
      t('healthchecks-and-restarts', 'Healthchecks and Restart Policy', 'liveness versus readiness, start periods, and a restart loop that hides the real error.', 'docker', ['containers-are-processes', 'systemd-and-services'], ['node-process-lifecycle']),
      t('resource-limits-and-oom', 'Resource Limits and OOM Kills', 'CPU shares, memory limits, the exit code 137, and Node\u2019s heap meeting the cgroup.', 'docker', ['resource-exhaustion-triage', 'containers-are-processes'], ['gc-memory-leaks']),
      t('compose-multi-service', 'Compose: Multi-Service Local Stack', 'api, web, database, cache, worker together, dependency order, and a reproducible boot.', 'docker', ['docker-networking', 'volumes-and-secrets'], ['healthchecks-and-restarts']),
    ],
  },
  {
    key: 'p21',
    number: 21,
    title: 'CI/CD',
    summary: 'A pipeline that proves something, ships immutably, and can be rolled back without courage.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('ci-pipeline-anatomy', 'Pipeline Anatomy', 'trigger, cache, install, check, build, artefact, deploy, and what each stage is asserting.', 'cicd', ['compose-multi-service', 'testing-pyramid'], ['shell-tooling']),
      t('ci-test-layers', 'What Runs on a PR and What Runs on Main', 'fast feedback, expensive suites on merge, flake quarantine, and the merge button that lies.', 'cicd', ['ci-pipeline-anatomy', 'integration-testing-real-deps'], ['load-stress-soak']),
      t('build-artifacts-and-immutability', 'Artifacts and Immutable Builds', 'build once, promote the same image, and why rebuilding for prod is a different test.', 'cicd', ['ci-pipeline-anatomy', 'images-and-layers'], ['volumes-and-secrets']),
      t('secrets-in-ci', 'Secrets in CI', 'masked output, scoped credentials, runners as hostile machines, and the log that leaked a key.', 'cicd', ['ci-pipeline-anatomy', 'volumes-and-secrets'], ['filesystem-permissions']),
      t('ci-migrations', 'Migrations in the Pipeline', 'expand then contract, gating a migration behind tests, and a rollback that is not a revert.', 'cicd', ['build-artifacts-and-immutability', 'orm-migrations-locking'], ['deterministic-tests']),
      t('deployment-strategies', 'Rolling, Blue/Green, Canary', 'traffic shifting, warm-up, abort criteria, and what each strategy costs in capacity.', 'cicd', ['build-artifacts-and-immutability', 'healthchecks-and-restarts'], ['service-discovery-and-load-balancing']),
      t('feature-flags-and-progressive-delivery', 'Feature Flags and Progressive Delivery', 'decoupling deploy from release, flag hygiene, and the flag that became architecture.', 'cicd', ['deployment-strategies'], ['domain-events']),
      t('rollback-and-recovery', 'Rollback Without Heroics', 'reversible changes, data that cannot be down-migrated, and the one-command recovery path.', 'cicd', ['deployment-strategies', 'ci-migrations']),
    ],
  },
  {
    key: 'p22',
    number: 22,
    title: 'Cloud and Production',
    summary: 'Cloud concepts over vendor memorisation: compute, storage, network, identity, failure domains.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('cloud-primitives', 'Cloud Primitives', 'compute, object storage, managed database, queue: the same four shapes in every provider\u2019s vocabulary.', 'cloud', ['compose-multi-service'], ['resource-modeling']),
      t('vpc-and-network-boundaries', 'VPC, Subnets and Network Boundaries', 'public versus private tiers, security groups as stateful firewalls, peering, egress paths.', 'cloud', ['cloud-primitives', 'networking-from-the-box'], ['docker-networking']),
      t('iam-and-least-privilege', 'IAM and Least Privilege', 'roles, policies, trust relationships, key rotation, and the wildcard you will regret.', 'security', ['cloud-primitives', 'filesystem-permissions'], ['vpc-and-network-boundaries']),
      t('managed-data-and-queues', 'Managed Databases and Queues', 'what you stop operating, what you cannot tune, and the bill that scales with your mistakes.', 'cloud', ['cloud-primitives', 'replication-and-quorum'], ['queue-anatomy', 'connection-pooling']),
      t('object-storage-and-cdn', 'Object Storage and CDN', 'presigned uploads, cache keys, invalidation, origin shield, and the file that must not be public.', 'cloud', ['cloud-primitives', 'proxies-load-balancers-cdn'], ['streams-backpressure']),
      t('autoscaling-and-elasticity', 'Autoscaling and Elasticity', 'scaling signals, cold starts, scale-down thrash, and the dependency that cannot take the new traffic.', 'cloud', ['scaling-statelessly', 'resource-limits-and-oom'], ['load-stress-soak']),
      t('backup-and-disaster-recovery', 'Backups and Disaster Recovery', 'RPO/RTO, restore drills that were never run, cross-region failure, and a backup that is corrupt.', 'cloud', ['wal-recovery', 'partial-failure'], ['replication-and-quorum', 'rollback-and-recovery']),
      t('multi-tenancy-and-failure-domains', 'Failure Domains and Blast Radius', 'zones, regions, quotas, rate limits, and designing for the day one of them is taken.', 'system-design', ['cloud-primitives', 'cap-and-pacelc'], ['autoscaling-and-elasticity']),
    ],
  },
  {
    key: 'p23',
    number: 23,
    title: 'Observability',
    summary: 'Answering "why is production slow?" with data you already have, not with guesses.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('observability-golden-signals', 'The Four Golden Signals', 'latency, traffic, errors, saturation, and the difference between a symptom and a cause.', 'observability', ['rate-limit-circuit-breaker', 'requirements-to-numbers'], ['node-libuv']),
      t('structured-logs', 'Structured Logs', 'levels, context, correlation IDs, log volume as a cost centre, and what must never be logged.', 'observability', ['api-versioning-tracing', 'log-forensics'], ['typed-boundaries']),
      t('distributed-tracing', 'Distributed Tracing', 'spans, context propagation, sampling choices, and the waterfall that shows one fat database call.', 'observability', ['api-versioning-tracing', 'partial-failure'], ['service-discovery-and-load-balancing']),
      t('metrics-and-alerting', 'Metrics and Alerting', 'counters, gauges, histograms, alert on symptoms not causes, and paging that people obey.', 'observability', ['observability-golden-signals', 'structured-logs'], ['heaps-priority-queues']),
      t('latency-at-every-layer', 'Latency at Every Layer', 'DNS, TLS, edge, balancer, app, pool, database, and a budget you can point at.', 'observability', ['url-to-render', 'distributed-tracing'], ['tcp-tls', 'connection-pooling']),
      t('debugging-production-slowness', 'Debugging Production Slowness', 'a runbook: bisect the layer, check saturation, read EXPLAIN, and prove the fix worked.', 'observability', ['metrics-and-alerting', 'latency-at-every-layer'], ['query-planner-explain', 'resource-exhaustion-triage']),
      t('slos-and-error-budgets', 'SLOs and Error Budgets', 'the target someone agreed to, the budget it spends, and what happens when it runs out.', 'system-design', ['observability-golden-signals', 'requirements-to-numbers'], ['capacity-and-cost']),
      t('incident-command-and-postmortem', 'Incident Command and Postmortem', 'severity, roles, comms, timeline reconstruction, and a write-up that changes a system.', 'observability', ['debugging-production-slowness', 'structured-logs'], ['rollback-and-recovery']),
    ],
  },
  {
    key: 'p24',
    number: 24,
    title: 'Security Engineering',
    summary: 'Trust boundaries, injection, broken access control, and the review that asks "who is allowed to?"',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('threat-modeling', 'Threat Modeling', 'assets, trust boundaries, entry points, and the abuse case a reviewer writes first.', 'security', ['boundaries-and-encapsulation', 'resource-modeling'], ['partial-failure']),
      t('authn-authz-sessions-tokens', 'Authentication, Authorization, Sessions, Tokens', 'who versus what, access versus refresh tokens, and the endpoint that checks the wrong identity.', 'security', ['cookies-cors-csrf', 'threat-modeling'], ['promises-async']),
      t('input-validation-and-injection', 'Validation and Injection', 'SQL, command, path, header, deserialisation, and why escaping at the sink beats filtering at the source.', 'security', ['type-vs-runtime-validation', 'sql-fundamentals', 'threat-modeling'], ['validation-error-contracts']),
      t('transport-and-headers', 'TLS, Headers and Cookie Flags', 'cipher config, HSTS, CSP, referrer policy, SameSite, and the mixed-content bug.', 'security', ['tcp-tls', 'cookies-cors-csrf'], ['object-storage-and-cdn']),
      t('secrets-and-crypto-hygiene', 'Secrets and Cryptography Hygiene', 'hashing versus encryption, KDF cost, rotation, envelope patterns, and home-grown ciphers.', 'security', ['authn-authz-sessions-tokens', 'system-calls-io'], ['volumes-and-secrets']),
      t('owasp-in-apis', 'OWASP in Real APIs', 'IDOR, BOLA, SSRF, mass assignment, broken object level checks found in a diff.', 'security', ['input-validation-and-injection', 'authn-authz-sessions-tokens'], ['resource-modeling']),
      t('supply-chain-and-dependencies', 'Supply Chain and Dependencies', 'lockfiles, registries, postinstall scripts, transitive risk, and the version that phoned home.', 'security', ['threat-modeling', 'build-artifacts-and-immutability'], ['secrets-in-ci']),
      t('security-review-mindset', 'The Security Review', 'review a design for exploitability, name the attack, the precondition, and the cheapest mitigation.', 'security', ['owasp-in-apis', 'threat-modeling'], ['transport-and-headers']),
    ],
  },
  {
    key: 'p25',
    number: 25,
    title: 'Performance Engineering',
    summary: 'Measure, attribute, fix, prove. Never optimise a feeling.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('measurement-before-optimisation', 'Measure Before You Touch Anything', 'baselines, percentiles versus averages, noise, and the p99 nobody plotted.', 'system-design', ['observability-golden-signals', 'complexity-analysis'], ['load-stress-soak']),
      t('cpu-and-heap-profiling', 'CPU and Heap Profiling', 'flame graphs, blocking the event loop, retained graphs, worker threads as the honest answer.', 'node', ['measurement-before-optimisation', 'gc-memory-leaks', 'resource-exhaustion-triage'], ['node-libuv']),
      t('database-performance', 'Database Performance', 'access pattern, index design, planner choices, keyset pagination, and the N+1 you shipped.', 'postgresql', ['query-planner-explain', 'indexes-btree', 'keyset-pagination'], ['n-plus-one', 'connection-pooling']),
      t('memory-and-cache-performance', 'Memory and Cache Performance', 'hit ratios you measured, allocation churn, cache lines, and the buffer you grew to "fix" latency.', 'system-design', ['cache-patterns', 'memory-hierarchy'], ['cache-stampede', 'gc-memory-leaks']),
      t('network-and-io-performance', 'Network and I/O Performance', 'RTT budgets, connection reuse, TLS handshakes, streaming versus buffering, disk patterns.', 'http', ['tcp-tls', 'streams-backpressure'], ['latency-at-every-layer', 'system-calls-io']),
      t('frontend-performance', 'Frontend Performance', 'bundle cost, waterfall, rendering work, Core Web Vitals, and the server component you thought was free.', 'react', ['react-performance', 'frontend-data-and-caching'], ['latency-at-every-layer']),
      t('throughput-under-load', 'Throughput Versus Latency Under Load', 'queuing behaviour, saturation knee, pool tuning, and the point where more workers make it worse.', 'distributed-systems', ['concurrency-budgets', 'measurement-before-optimisation'], ['load-stress-soak', 'autoscaling-and-elasticity']),
      t('performance-regressions-in-ci', 'Catching Regressions Before Prod', 'perf budgets in the pipeline, noisy neighbours, and the benchmark you can trust.', 'cicd', ['ci-test-layers', 'measurement-before-optimisation'], ['throughput-under-load']),
    ],
  },
  {
    key: 'p26',
    number: 26,
    title: 'Git Deep Mastery',
    summary: 'The object model, review craft, and recovering history without panic.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('git-object-model', 'The Git Object Model', 'commits, trees, blobs, refs, and what a branch actually is when you can draw it.', 'linux', ['how-programs-run', 'filesystem-permissions'], ['data-modeling']),
      t('branching-and-merging', 'Branching, Merging, Rebasing', 'merge strategies, conflict resolution that keeps both intents, and history you should not rewrite.', 'linux', ['git-object-model'], ['concurrency-parallelism']),
      t('history-rewriting-and-recovery', 'Rewriting History and Recovering It', 'interactive rebase, reflog, bisect, revert of a merge, and the commit you thought was gone.', 'linux', ['branching-and-merging'], ['shell-tooling']),
      t('review-craft', 'Code Review as Engineering', 'reading a diff for risk, small PRs, naming the failure mode, and the comment that prevents one.', 'leadership', ['branching-and-merging', 'solid-as-consequences'], ['deterministic-tests']),
      t('monorepo-and-large-repos', 'Large Repos and Monorepos', 'sparse checkout, submodule versus workspace, CI impact graphs, and history that slows every clone.', 'linux', ['history-rewriting-and-recovery'], ['ci-pipeline-anatomy']),
    ],
  },
  {
    key: 'p27',
    number: 27,
    title: 'AI Fundamentals',
    summary: 'Tokens, sampling, embeddings, context windows: the machine behind the API call.',
    tracks: ['agentic-ai'],
    topics: [
      t('tokens-and-tokenisation', 'Tokens and Tokenisation', 'BPE, why costs and limits are counted in tokens, and the multilingual text that triples them.', 'llm', ['type-vs-runtime-validation'], ['complexity-analysis']),
      t('how-llms-generate', 'How an LLM Produces Text', 'next-token distribution, temperature, top-p, stop conditions, context window, KV cache.', 'llm', ['tokens-and-tokenisation'], ['memory-hierarchy', 'cpu-bound-vs-io-bound']),
      t('embeddings-and-similarity', 'Embeddings and Similarity', 'vector space, cosine versus dot, what a distance of 0.31 actually claims.', 'llm', ['how-llms-generate'], ['hash-tables', 'complexity-analysis']),
      t('prompt-as-interface', 'The Prompt as an Interface', 'instruction versus context versus examples, and why a prompt deserves a contract.', 'llm', ['how-llms-generate'], ['typed-boundaries']),
      t('llm-nondeterminism', 'Nondeterminism and What It Breaks', 'same input, different output, seeds and temperature, and the assertion that cannot be exact.', 'llm', ['prompt-as-interface'], ['deterministic-tests']),
      t('model-selection-and-cost', 'Choosing a Model', 'capability tiers, latency, cost per token, and the smaller model you must evaluate to prove.', 'llm', ['how-llms-generate'], ['capacity-and-cost']),
      t('fine-tuning-vs-retrieval-vs-prompting', 'Prompting versus Retrieval versus Fine-Tuning', 'which problem each one actually solves, and the order you should try them in.', 'llm', ['embeddings-and-similarity', 'llm-nondeterminism'], ['database-performance']),
    ],
  },
  {
    key: 'p28',
    number: 28,
    title: 'LLM Application Engineering',
    summary: 'LLM calls as production dependencies: timeouts, budgets, structured output, streaming.',
    tracks: ['agentic-ai'],
    topics: [
      t('llm-call-hygiene', 'LLM Call Hygiene', 'timeouts, retry budgets, rate limits, token accounting, and treating a vendor as flaky infra.', 'llm', ['llm-nondeterminism', 'timeout-and-retry-budgets'], ['observability-golden-signals']),
      t('structured-output-and-tool-calls', 'Structured Output and Tool Calls', 'JSON schemas, function calling, repair loops, and validating at the boundary you do not control.', 'llm', ['structural-typing', 'prompt-as-interface', 'llm-call-hygiene'], ['validation-error-contracts']),
      t('context-engineering', 'Context Engineering', 'window budgeting, ordering, relevance, eviction, and the summary that quietly deleted an invariant.', 'llm', ['prompt-as-interface', 'tokens-and-tokenisation'], ['memory-hierarchy']),
      t('llm-streaming-and-cancellation', 'Streaming, Latency and Cancellation', 'time to first token, SSE, abort propagation, and the cost of a stream nobody closed.', 'llm', ['streams-backpressure', 'llm-call-hygiene'], ['frontend-data-and-caching']),
      t('llm-in-backend-apis', 'LLM Work Inside an API', 'long calls off the request path, job status, partial results, idempotency for expensive retries.', 'nestjs', ['nestjs-queues-events', 'structured-output-and-tool-calls', 'idempotency-under-concurrency'], ['async-pipelines']),
      t('prompt-and-model-versioning', 'Prompt and Model Versioning', 'prompts as deployed artefacts, pinning a model, and the upgrade nobody regression-tested.', 'llm', ['structured-output-and-tool-calls'], ['api-versioning-tracing', 'ci-migrations']),
      t('cost-latency-quality-trilemma', 'Cost, Latency, Quality', 'the three knobs, the trade you are forced to make per feature, and the number that decides it.', 'llm', ['model-selection-and-cost', 'llm-call-hygiene'], ['slos-and-error-budgets']),
    ],
  },
  {
    key: 'p29',
    number: 29,
    title: 'Retrieval-Augmented Generation',
    summary: 'Vector search is an index problem before it is an embedding problem.',
    tracks: ['agentic-ai'],
    topics: [
      t('chunking-and-indexing', 'Chunking and Indexing', 'chunk strategy, overlap, parent documents, and the boundary that split the answer in half.', 'rag', ['embeddings-and-similarity', 'context-engineering'], ['data-modeling']),
      t('vector-index-internals', 'Vector Index Internals', 'exact versus ANN, HNSW and IVF, recall versus latency, and the parameter nobody tuned.', 'rag', ['chunking-and-indexing', 'trees-and-indexes'], ['complexity-analysis']),
      t('retrieval-quality', 'Retrieval Quality', 'hybrid search, reranking, recall@k and MRR, and the query that needed a JOIN not a cosine.', 'rag', ['vector-index-internals', 'sql-window-cte'], ['llm-nondeterminism']),
      t('postgres-as-vector-store', 'Postgres as the Vector Store', 'pgvector, index choice, filtering by metadata in the same query, and one database to operate.', 'postgresql', ['indexes-btree', 'vector-index-internals'], ['orm-query-generation', 'connection-pooling']),
      t('rag-pipeline-engineering', 'The Ingest Pipeline', 'extraction, dedupe, freshness, backfills, deletion propagation, and the source of truth you shadow.', 'rag', ['retrieval-quality', 'outbox-in-practice'], ['ci-migrations', 'queue-anatomy']),
      t('grounding-and-citations', 'Grounding and Citations', 'forcing the model onto retrieved text, citation integrity, and the answer with no source.', 'rag', ['rag-pipeline-engineering', 'structured-output-and-tool-calls'], ['prompt-and-model-versioning']),
      t('hallucination-and-refusal', 'Hallucination and the Correct Refusal', 'why plausible text appears, detection, and designing "I don\u2019t have that" as a feature.', 'rag', ['retrieval-quality', 'grounding-and-citations'], ['llm-nondeterminism']),
      t('when-rag-is-wrong', 'When Not to Build RAG', 'SQL, search, briefing documents, workflows, agents: the alternatives and their evidence.', 'rag', ['hallucination-and-refusal', 'rag-pipeline-engineering'], ['design-method', 'fine-tuning-vs-retrieval-vs-prompting']),
    ],
  },
];
