import { t } from './build';
import type { PhaseSpec } from './types';

export const PHASES_10_19: PhaseSpec[] = [
  {
    key: 'p10',
    number: 10,
    title: 'Frontend Engineering',
    summary: 'React and Next.js as a rendering problem: where code executes, and what state costs.',
    tracks: ['fullstack'],
    topics: [
      t('rendering-and-reconciliation', 'Rendering and Reconciliation', 'element trees, keys, why a re-render is not a DOM write, and what React actually diffs.', 'react', ['js-values-references'], ['closures-scope']),
      t('state-and-effects', 'State, Effects and Cleanup', 'state as data, lifting, effects as the escape hatch, dependency arrays, stale closures.', 'react', ['rendering-and-reconciliation', 'closures-scope'], ['event-loop']),
      t('component-architecture', 'Component Architecture', 'composition over configuration, props contracts, custom hooks, feature boundaries.', 'react', ['state-and-effects']),
      t('react-performance', 'React Performance', 'memo/useMemo/useCallback and their own cost, list virtualisation, profiler reading.', 'react', ['state-and-effects'], ['complexity-analysis', 'gc-memory-leaks']),
      t('server-vs-client-boundary', 'Where Should This Code Execute?', 'client, server, database, worker, AI service: the decision that matters more than API syntax.', 'nextjs', ['component-architecture', 'url-to-render'], ['resource-modeling']),
      t('nextjs-rendering-strategies', 'App Router and Rendering Strategies', 'RSC vs client components, SSR/ISR/CSR, streaming, loading and error boundaries, server actions.', 'nextjs', ['server-vs-client-boundary'], ['http-versions', 'promises-async']),
      t('frontend-data-and-caching', 'Server State, Client State, Revalidation', 'query caching, invalidation on the client, optimistic updates and their rollback.', 'nextjs', ['nextjs-rendering-strategies', 'http-caching'], ['cache-invalidation']),
      t('frontend-auth', 'Authentication in a Next.js App', 'sessions across SSR, middleware, route protection, and the token you should not render.', 'nextjs', ['nextjs-rendering-strategies', 'cookies-cors-csrf']),
      t('accessibility-and-feedback', 'Accessibility and Feedback States', 'semantics, focus order, and designing loading, empty, partial and error states on purpose.', 'react', ['component-architecture'], ['frontend-data-and-caching']),
    ],
  },
  {
    key: 'p11',
    number: 11,
    title: 'Software Design',
    summary: 'Design principles as consequences of pain, not vocabulary to quote in a review.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('cohesion-coupling', 'Cohesion and Coupling', 'why things change together, and what a change ripple actually costs.', 'system-design', ['structural-typing'], ['generics']),
      t('dependency-inversion', 'Dependency Inversion', 'depend on the abstraction you can substitute, not the one you can grep.', 'system-design', ['cohesion-coupling'], ['nestjs-di']),
      t('solid-as-consequences', 'SOLID as Consequences', 'each principle as a bad implementation, the pain it caused, the refactor, and when not to apply it.', 'system-design', ['cohesion-coupling', 'dependency-inversion']),
      t('abstraction-and-composition', 'Abstraction, Composition, Interfaces', 'seams, composition over inheritance, and the abstraction that is really a leak.', 'system-design', ['solid-as-consequences', 'prototypes'], ['generics']),
      t('domain-modeling-basics', 'Domain Modeling', 'entities, value objects, invariants, and a language the code and the business share.', 'system-design', ['solid-as-consequences', 'data-modeling']),
      t('boundaries-and-encapsulation', 'Boundaries and Information Hiding', 'public surface, module contracts, and what must not reach across the line.', 'system-design', ['abstraction-and-composition'], ['typed-boundaries']),
    ],
  },
  {
    key: 'p12',
    number: 12,
    title: 'Clean Architecture',
    summary: 'Layers, ports, bounded contexts, and the discipline of not extracting a microservice.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('layered-architecture', 'Layered Architecture', 'presentation, application, domain, infrastructure, and which direction is allowed to import which.', 'system-design', ['domain-modeling-basics', 'nestjs-pipeline'], ['boundaries-and-encapsulation']),
      t('hexagonal-ports-adapters', 'Hexagonal Architecture: Ports and Adapters', 'the driving side, the driven side, and a domain that boots without a database.', 'system-design', ['layered-architecture', 'dependency-inversion']),
      t('clean-architecture', 'The Dependency Rule', 'use cases at the centre, frameworks at the edge, and why arrows only point inward.', 'system-design', ['hexagonal-ports-adapters', 'solid-as-consequences']),
      t('ddd-building-blocks', 'DDD Building Blocks', 'aggregates, domain services, repositories, unit of work, and invariants that hold under concurrency.', 'system-design', ['clean-architecture', 'domain-modeling-basics'], ['locks-deadlocks']),
      t('domain-events', 'Domain Events', 'facts that already happened, in-process vs out-of-process, and what a lost event costs.', 'system-design', ['ddd-building-blocks'], ['event-loop']),
      t('bounded-contexts', 'Bounded Contexts', 'the same word meaning two things in two systems, and the model that has to accept it.', 'system-design', ['ddd-building-blocks', 'domain-events']),
      t('modular-monolith', 'The Modular Monolith', 'enforced module boundaries inside one deployable, and the tests that keep them honest.', 'system-design', ['bounded-contexts', 'clean-architecture'], ['nestjs-di']),
      t('anti-corruption-layer', 'Anti-Corruption Layers', 'translating a hostile external model before it infects yours.', 'system-design', ['bounded-contexts'], ['hexagonal-ports-adapters']),
      t('microservices-decomposition', 'When NOT to Use Microservices', 'extract a service only on a justified axis: scaling, team, failure isolation, deploy cadence.', 'system-design', ['modular-monolith', 'bounded-contexts']),
    ],
  },
  {
    key: 'p13',
    number: 13,
    title: 'Design Patterns',
    summary: 'Patterns indexed by the problem they remove, including the state machine you build before buying one.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('pattern-by-problem', 'Reading a Pattern as a Problem', 'problem, naive implementation, the pain, the pattern, the trade-off it accepts.', 'system-design', ['solid-as-consequences']),
      t('creational-patterns', 'Factory and Builder', 'what construction complexity is hiding, and which pattern removes it.', 'system-design', ['pattern-by-problem', 'prototypes'], ['generics']),
      t('strategy-observer-command', 'Strategy, Observer, Command', 'swappable behaviour, fan-out notification, and work as a re-playable object.', 'system-design', ['pattern-by-problem', 'abstraction-and-composition'], ['domain-events']),
      t('adapter-decorator-proxy', 'Adapter, Decorator, Proxy', 'shaping an interface you do not control, adding behaviour without touching it.', 'system-design', ['pattern-by-problem'], ['hexagonal-ports-adapters', 'anti-corruption-layer']),
      t('state-machines-handrolled', 'State Machines From Scratch', 'build one without a library: states, transitions, guards, illegal moves made unrepresentable.', 'system-design', ['strategy-observer-command', 'narrowing-unions'], ['recursion']),
      t('chain-and-repository', 'Chain of Responsibility, Repository, Unit of Work', 'pipeline handlers, persistence behind a collection-like interface, one commit boundary.', 'system-design', ['adapter-decorator-proxy', 'ddd-building-blocks']),
      t('resilience-patterns', 'Retry, Circuit Breaker, Bulkhead', 'timeout budgets, failure policies, and the difference between retrying and amplifying.', 'system-design', ['adapter-decorator-proxy', 'rate-limit-circuit-breaker'], ['idempotency-retries']),
      t('saga-and-outbox', 'Saga and Outbox', 'compensation instead of rollback, and the atomic write that makes an event trustworthy.', 'distributed-systems', ['resilience-patterns', 'domain-events'], ['mvcc-isolation']),
    ],
  },
  {
    key: 'p14',
    number: 14,
    title: 'Testing',
    summary: 'What each layer of tests proves, what it cannot prove, and what it costs to keep.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('testing-pyramid', 'The Testing Pyramid and Its Lies', 'unit, integration, contract, e2e: coverage of risk, not coverage of lines.', 'testing', ['type-vs-runtime-validation', 'validation-error-contracts'], ['resource-modeling']),
      t('test-doubles', 'Mocks, Stubs, Spies, Fakes', 'which double you actually need, and the suite that tests its own mocks.', 'testing', ['testing-pyramid', 'dependency-inversion']),
      t('deterministic-tests', 'Determinism and Flake Elimination', 'time, randomness, ordering, parallel isolation, and why retries hide real bugs.', 'testing', ['testing-pyramid', 'promises-async'], ['node-libuv']),
      t('integration-testing-real-deps', 'Integration Tests Against Real Dependencies', 'real database, real schema, transaction rollback per test, containers where they pay for themselves.', 'testing', ['test-doubles', 'orm-transactions-pooling'], ['connection-pooling']),
      t('e2e-testing', 'End-to-End Tests', 'user journeys, selector strategy, and the CI bill every e2e test sends you.', 'testing', ['deterministic-tests'], ['nextjs-rendering-strategies', 'url-to-render']),
      t('contract-testing', 'Contract Tests Across Boundaries', 'producer/consumer agreements, breaking a client before it breaks production.', 'testing', ['integration-testing-real-deps', 'resource-modeling'], ['api-versioning-tracing']),
      t('property-and-mutation-testing', 'Property-Based and Mutation Testing', 'assert invariants over inputs, then check whether your suite notices a seeded bug.', 'testing', ['test-doubles'], ['narrowing-unions', 'complexity-analysis']),
      t('load-stress-soak', 'Load, Stress, Soak', 'throughput ceilings, latency under pressure, and the leak that only appears at hour nine.', 'testing', ['integration-testing-real-deps'], ['node-process-lifecycle', 'query-planner-explain']),
      t('testing-broken-code', 'Testing a Broken Implementation', 'read faulty code, write the tests that expose it, and name the failure mode.', 'testing', ['test-doubles', 'deterministic-tests'], ['property-and-mutation-testing']),
    ],
  },
  {
    key: 'p15',
    number: 15,
    title: 'Concurrency',
    summary: 'Interleaving is the bug. Two users, one last item, one webhook, twice.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('race-conditions', 'Race Conditions', 'interleavings, shared mutable state, check-then-act, and reproducing a heisenbug on purpose.', 'distributed-systems', ['event-loop', 'mvcc-isolation'], ['promises-async']),
      t('locks-mutex-semaphore', 'Locks, Mutexes, Semaphores', 'in-process and cross-process, contention, starvation, and the lock you should not need.', 'distributed-systems', ['race-conditions', 'locks-deadlocks'], ['concurrency-parallelism']),
      t('optimistic-vs-pessimistic', 'Optimistic and Pessimistic Concurrency', 'version columns versus SELECT FOR UPDATE, conflict rates, and who pays for the retry.', 'postgresql', ['locks-mutex-semaphore', 'orm-migrations-locking']),
      t('idempotency-under-concurrency', 'Idempotency Under Concurrency', 'duplicate webhooks, double payments, idempotency keys and their storage semantics.', 'distributed-systems', ['race-conditions', 'idempotency-retries'], ['wal-recovery']),
      t('distributed-locking-correctness', 'Distributed Locking Correctness', 'leases, fencing tokens, GC pauses, clock skew, and the claim a lock is always wrong.', 'distributed-systems', ['distributed-locks', 'locks-mutex-semaphore'], ['node-process-lifecycle']),
      t('backpressure-and-queues', 'Backpressure and Bounded Queues', 'what to do when the producer outruns the consumer: block, drop, shed, or degrade.', 'node', ['streams-backpressure', 'locks-mutex-semaphore'], ['connection-pooling']),
      t('concurrency-budgets', 'Concurrency Budgets and Little\u2019s Law', 'pool sizes, in-flight limits, throughput versus latency, and where adding workers hurts.', 'node', ['backpressure-and-queues', 'node-libuv'], ['cpu-bound-vs-io-bound']),
    ],
  },
  {
    key: 'p16',
    number: 16,
    title: 'Distributed Systems',
    summary: 'Partial failure is the normal case. Every design has to survive a network that lies.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('partial-failure', 'Partial Failure', 'the system that is up for one request and down for another, and what that does to your assumptions.', 'distributed-systems', ['networking-basics', 'race-conditions'], ['node-process-lifecycle']),
      t('time-ordering-and-clocks', 'Time, Ordering and Clocks', 'wall clocks lie, logical and vector time, and what "first" means without a coordinator.', 'distributed-systems', ['partial-failure'], ['system-calls-io']),
      t('consistency-models', 'Consistency Models', 'strong, eventual, read-your-writes, monotonic reads, and the one your product promises.', 'distributed-systems', ['time-ordering-and-clocks', 'mvcc-isolation']),
      t('replication-and-quorum', 'Replication and Quorum', 'leader/follower, read/write quorums, replication lag, and what N=3 really buys.', 'distributed-systems', ['consistency-models'], ['wal-recovery']),
      t('cap-and-pacelc', 'CAP and PACELC', 'the choice you are forced into when the partition arrives, and the latency half nobody quotes.', 'distributed-systems', ['consistency-models', 'partial-failure']),
      t('network-partitions-and-failover', 'Partitions, Split Brain, Fencing', 'leader election, stale leaders still writing, and the mechanism that makes them stop.', 'distributed-systems', ['replication-and-quorum', 'distributed-locking-correctness']),
      t('service-discovery-and-load-balancing', 'Service Discovery and Load Balancing', 'registration, health, churn, sticky routing, and the cache that is now wrong.', 'system-design', ['proxies-load-balancers-cdn', 'partial-failure'], ['connection-pooling']),
      t('timeout-and-retry-budgets', 'Timeout and Retry Budgets', 'deadline propagation, retry storms, hedged requests, and per-hop vs end-to-end budgets.', 'distributed-systems', ['resilience-patterns', 'partial-failure'], ['concurrency-budgets']),
      t('distributed-transactions-and-sagas', 'Distributed Transactions and Sagas', "Service A committed, Service B is down: orchestration, choreography, and honest compensation.", 'distributed-systems', ['saga-and-outbox', 'cap-and-pacelc'], ['optimistic-vs-pessimistic']),
    ],
  },
  {
    key: 'p17',
    number: 17,
    title: 'Message Queues and Event-Driven Systems',
    summary: 'Build the job pipeline, then break every component in it and watch what the queue does.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('queue-anatomy', 'Queue Anatomy', 'broker, producer, consumer, acknowledgement, visibility timeout, in-flight state.', 'distributed-systems', ['concurrency-budgets', 'redis-queues-delayed-jobs'], ['node-libuv']),
      t('queue-delivery-semantics', 'Delivery Semantics', 'at-most-once, at-least-once, and the exactly-once claim someone always makes.', 'distributed-systems', ['queue-anatomy', 'idempotency-under-concurrency']),
      t('dead-letters-and-retry-policy', 'Dead Letters and Retry Policy', 'backoff, jitter, poison messages, and the alert nobody configured.', 'distributed-systems', ['queue-delivery-semantics', 'timeout-and-retry-budgets'], ['queue-anatomy']),
      t('ordering-and-partitioning', 'Ordering and Partitioning', 'per-key ordering, partition choice, rebalances, and what reordering breaks downstream.', 'distributed-systems', ['queue-delivery-semantics', 'time-ordering-and-clocks'], ['heaps-priority-queues']),
      t('idempotent-consumers', 'Idempotent Consumers', 'duplicate delivery as a guarantee, dedupe keys, and state machines that tolerate replays.', 'distributed-systems', ['idempotency-under-concurrency', 'queue-delivery-semantics'], ['state-machines-handrolled']),
      t('outbox-in-practice', 'The Outbox in Practice', 'commit the fact, then publish it, and never again write to two systems in one request.', 'distributed-systems', ['saga-and-outbox', 'queue-delivery-semantics', 'domain-events'], ['optimistic-vs-pessimistic']),
      t('worker-pools-and-throughput', 'Worker Pools and Throughput', 'consumer count, batch size, prefetch, and the queue that drains slower every week.', 'distributed-systems', ['queue-anatomy', 'concurrency-budgets'], ['load-stress-soak']),
      t('event-driven-architecture', 'Event-Driven Architecture', 'events versus commands, schemas, versioning, and a consumer that no one owns.', 'system-design', ['outbox-in-practice', 'ordering-and-partitioning'], ['bounded-contexts']),
    ],
  },
  {
    key: 'p18',
    number: 18,
    title: 'System Design',
    summary: 'Foundations first \u2014 the brief, the budgets, the arithmetic \u2014 then requirements, APIs, storage, failure, cost, trade-offs.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      // The foundations block reads in order, so its internal edges are advisory: these topics carry
      // no drills yet, and a critical edge would gate lesson 02 behind an L3 nobody can earn.
      t('sd-requirements-clarification', 'Requirements Clarification', 'the verbs, the budgets and the exclusions: a one-page brief that makes every later choice arguable.', 'system-design', ['complexity-analysis', 'networking-basics'], ['data-modeling']),
      t('sd-logical-system-design', 'Logical Before Physical', 'processes, stores and contracts first; the products are derived from them, not the other way round.', 'system-design', ['resource-modeling'], ['sd-requirements-clarification', 'boundaries-and-encapsulation']),
      t('sd-non-functional-requirements', 'Non-Functional Requirements as Budgets', 'latency, availability, durability, retention, recovery, cost \u2014 each a number, a window, a measurement and an owner.', 'system-design', ['complexity-analysis'], ['sd-requirements-clarification', 'rate-limit-circuit-breaker']),
      t('sd-tradeoff-language', 'The Trade-off Column', 'every design is a purchase: what it buys, what it costs, what was rejected, and what would flip the call.', 'system-design', ['cohesion-coupling'], ['sd-non-functional-requirements', 'sd-requirements-clarification']),
      t('sd-availability-durability-consistency-cost', 'Availability, Durability, Consistency, Cost', 'four independent dials, each produced by a mechanism, and cost is the price of the other three set to a position.', 'system-design', ['consistency-models'], ['cap-and-pacelc', 'sd-tradeoff-language']),
      t('sd-capacity-arithmetic', 'Back-of-the-Envelope Capacity Arithmetic', 'users to QPS to bytes to years in three minutes, including the peak factor and the index multiplier that wreck plans.', 'system-design', ['networking-basics', 'complexity-analysis'], ['sd-non-functional-requirements', 'proxies-load-balancers-cdn']),
      t('sd-handling-many-requests', 'How One Server Handles Many Requests', 'thread-per-connection, the event loop, the worker pool: what each costs per idle socket and where each one dies.', 'system-design', ['event-loop', 'processes-threads'], ['cpu-bound-vs-io-bound', 'sd-capacity-arithmetic']),
      t('sd-horizontal-vs-vertical-scaling', 'Horizontal and Vertical Scaling', 'the state that leaks into the box, the ceiling you cannot buy, and the pool math that makes scale-out real.', 'system-design', ['service-discovery-and-load-balancing'], ['sd-handling-many-requests', 'connection-pooling']),
      t('sd-monolith-vs-services', 'Monolith, Modular Monolith, Services', 'a service boundary is a data and team decision, and every hop adds latency, failure semantics and a pager.', 'system-design', ['bounded-contexts'], ['sd-logical-system-design', 'clean-architecture']),
      t('sd-repository-pattern', 'The Repository Pattern', 'a domain-shaped collection over storage: where it pays, where it is indirection, and where the transaction belongs.', 'system-design', ['ddd-building-blocks'], ['layered-architecture', 'sd-monolith-vs-services']),
      t('sd-extensible-data-modeling', 'Extensible Data Modeling', 'model the changes you cannot predict: the column-before-table ladder, expand-migrate-contract, and the JSON trap.', 'system-design', ['data-modeling'], ['sql-fundamentals', 'sd-repository-pattern']),
      t('sd-cost-aware-architecture', 'Cost as a Design Input', 'cost per request is mostly structural, so the bill is decided by the diagram rather than by the instance size.', 'system-design', ['proxies-load-balancers-cdn'], ['sd-capacity-arithmetic', 'cache-patterns']),
      t('sd-when-not-to-add-infrastructure', 'When Not to Add Infrastructure', 'each component is a pager, a failure mode and an upgrade; the escalation ladder has a measured trigger per rung.', 'system-design', ['boundaries-and-encapsulation'], ['sd-monolith-vs-services', 'sd-cost-aware-architecture']),
      t('requirements-to-numbers', 'Requirements into Numbers', 'functional and non-functional, traffic, data volume, growth, and the estimate that decides storage.', 'system-design', ['complexity-analysis', 'networking-basics'], ['data-modeling']),
      t('api-and-storage-design', 'API and Storage Design', 'resource model, access patterns, and the storage choice that follows from the queries, not the hype.', 'system-design', ['resource-modeling', 'data-modeling'], ['sql-fundamentals']),
      t('scaling-statelessly', 'Scaling Without State', 'horizontal scaling, stateless services, the sticky-session trap, and pooling behind a balancer.', 'system-design', ['service-discovery-and-load-balancing', 'connection-pooling'], ['concurrency-budgets']),
      t('caching-in-design', 'Caching End to End', 'CDN, edge, application, database cache layers, and which one you can afford to be wrong.', 'system-design', ['cache-patterns', 'http-caching'], ['cache-invalidation', 'cache-stampede']),
      t('async-pipelines', 'Asynchronous Pipelines', 'what to move off the request path, how the client learns the result, and the queue that becomes the product.', 'system-design', ['queue-anatomy', 'worker-pools-and-throughput'], ['event-driven-architecture']),
      t('design-method', 'The Design Method', 'the seventeen steps as one habit, and the three questions: what breaks first, how would you know, how do you fix it.', 'system-design', ['requirements-to-numbers', 'api-and-storage-design'], ['bounded-contexts', 'cap-and-pacelc']),
      t('capacity-and-cost', 'Capacity, Cost and Limits', 'cost per request, provisioned versus elastic, and the number that kills the elegant design.', 'system-design', ['requirements-to-numbers'], ['scaling-statelessly', 'load-stress-soak']),
      t('design-read-heavy', 'Designing Read-Heavy Systems', 'feeds, search, timelines: fan-out, precomputation, and freshness you can defend.', 'system-design', ['design-method', 'caching-in-design'], ['keyset-pagination', 'tries-autocomplete']),
      t('design-write-heavy', 'Designing Write-Heavy Systems', 'payments, bookings, orders: correctness under concurrency, idempotency, auditability.', 'system-design', ['design-method', 'distributed-transactions-and-sagas'], ['idempotency-under-concurrency']),
      t('design-realtime', 'Designing Real-Time Systems', 'chat, presence, notifications: long-lived connections, delivery states, and backpressure at scale.', 'system-design', ['design-method', 'ordering-and-partitioning'], ['streams-backpressure', 'frontend-data-and-caching']),
    ],
  },
  {
    key: 'p19',
    number: 19,
    title: 'Linux',
    summary: 'Troubleshooting a real incident from terminal output, not memorising flags.',
    tracks: ['backend', 'fullstack', 'agentic-ai'],
    topics: [
      t('processes-signals-priority', 'Processes, Signals, Priority', 'ps/top/htop, process states, signals a Node process actually handles, nice and load.', 'linux', ['processes-threads'], ['node-process-lifecycle']),
      t('filesystem-permissions', 'Filesystem and Permissions', 'inodes, file modes, users and groups, umask, and the EACCES you have to explain.', 'linux', ['system-calls-io'], ['how-programs-run']),
      t('shell-tooling', 'Shell Tooling', 'grep, awk, sed, find, xargs, and building the pipeline that finds the failing request.', 'linux', ['filesystem-permissions']),
      t('systemd-and-services', 'systemd and Service Lifecycle', 'units, restart policy, environment, journalctl, and why PM2 was never production.', 'linux', ['processes-signals-priority'], ['node-process-lifecycle']),
      t('networking-from-the-box', 'Networking From the Box', 'ss, lsof, dig, curl -v, sockets, ports, and proving where the connection actually dies.', 'linux', ['tcp-tls', 'system-calls-io'], ['dns-resolution']),
      t('resource-exhaustion-triage', 'Resource Exhaustion Triage', 'CPU, memory, disk, file descriptors, load average, and free/df/du reading under pressure.', 'linux', ['processes-signals-priority', 'filesystem-permissions'], ['gc-memory-leaks']),
      t('log-forensics', 'Log Forensics', 'journalctl, rotated logs, correlation IDs across files, and reconstructing a timeline.', 'observability', ['shell-tooling'], ['api-versioning-tracing']),
      t('incident-from-terminal-output', 'Incident Triage From Terminal Output', 'given raw output, name the fault, the cause, and the next two commands.', 'linux', ['resource-exhaustion-triage', 'networking-from-the-box'], ['log-forensics']),
    ],
  },
];
